#if !defined(AFX_PEDIT_H__A38ACA4F_F553_4C3A_BD4C_25C6F1EBC7B1__INCLUDED_)
#define AFX_PEDIT_H__A38ACA4F_F553_4C3A_BD4C_25C6F1EBC7B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPEdit wrapper class

class CPEdit : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPEdit)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x9c7461e3, 0x5dde, 0x4ecd, { 0xb5, 0x39, 0x67, 0x2b, 0x96, 0xef, 0x12, 0xcc } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetAutoHScroll();
	void SetAutoHScroll(BOOL);
	BOOL GetPassword();
	void SetPassword(BOOL);
	BOOL GetBorder();
	void SetBorder(BOOL);
	BOOL GetReadOnly();
	void SetReadOnly(BOOL);
	BOOL GetClientEdge();
	void SetClientEdge(BOOL);
	BOOL GetStaticEdge();
	void SetStaticEdge(BOOL);
	BOOL GetModalFrame();
	void SetModalFrame(BOOL);
	BOOL GetRight();
	void SetRight(BOOL);
	CString GetFontName();
	void SetFontName(LPCTSTR);
	long GetFontSize();
	void SetFontSize(long);
	short GetFontSet();
	void SetFontSet(short);

// Operations
public:
	long GetLength();
	CString GetText();
	void SetText(LPCTSTR str);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PEDIT_H__A38ACA4F_F553_4C3A_BD4C_25C6F1EBC7B1__INCLUDED_)
